import turtle
pen = turtle.Turtle()
def draw_slice(start_point, angle, color):
  pen.speed(0)
  pen.hideturtle()
  pen.goto(start_point)
  pen.fillcolor(color)
  pen.begin_fill()
  pen.circle(50,angle)
  end_point = pen.pos()
  pen.left(90)
  pen.forward(50)
  center_point = pen.pos()
  pen.goto(start_point)
  pen.end_fill()
  pen.goto(center_point)
  pen.right(90)
  pen.goto(end_point)
  return end_point
next_start_point = draw_slice((0, 0), 360, 'black')
draw_slice(next_start_point, 0, 'orange')
print("Black = Roblox")